"""init

Revision ID: d494e9f1108d
Revises: e0a085c416eb
Create Date: 2026-06-30 06:29:01.841398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd494e9f1108d'
down_revision: Union[str, None] = 'e0a085c416eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
