"""init

Revision ID: dc45d011f68e
Revises: 
Create Date: 2026-06-29 22:10:56.080474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc45d011f68e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eglises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('district', sa.Enum('OUEST', 'EST', 'CENTRE', 'SUD', 'OUTREMER', name='district'), nullable=False),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('membres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('eglise_id', sa.UUID(), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('statut_familial', sa.String(length=50), nullable=True),
    sa.Column('statut_bapteme', sa.String(length=20), nullable=False),
    sa.Column('statut_adhesion', sa.Enum('EN_ATTENTE', 'APPROUVE', 'REFUSE', name='statutadhesion'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['eglise_id'], ['eglises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('sermons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('predicateur', sa.String(length=255), nullable=False),
    sa.Column('date_sermon', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('serie', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('fichier_key', sa.String(length=500), nullable=True),
    sa.Column('format', sa.Enum('AUDIO', 'VIDEO', name='formatsermon'), nullable=False),
    sa.Column('duree_secondes', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('BROUILLON', 'PUBLIE', 'ARCHIVE', name='statutsermon'), nullable=False),
    sa.Column('vues', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sermons')
    op.drop_table('membres')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('eglises')
    # ### end Alembic commands ###
