"""init

Revision ID: e0a085c416eb
Revises: dc45d011f68e
Create Date: 2026-06-30 02:43:15.291866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0a085c416eb'
down_revision: Union[str, None] = 'dc45d011f68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
